### ISSUE TITLE
java.lang.ClassCastException: net.certiv.fluentmark.model.PageRoot cannot be cast to net.certiv.fluentmark.model.PagePart

### ISSUE THREAD

**Issue by paulvi** [grosenberg/fluentmark#21]
```
java.lang.ClassCastException: net.certiv.fluentmark.model.PageRoot cannot be cast to net.certiv.fluentmark.model.PagePart
	at net.certiv.fluentmark.model.PageRoot.addToParent(PageRoot.java:474)
	at net.certiv.fluentmark.model.PageRoot.parse(PageRoot.java:383)
	at net.certiv.fluentmark.model.PageRoot.updateModel(PageRoot.java:138)
	at net.certiv.fluentmark.editor.FluentMkEditor.updatePageModel(FluentMkEditor.java:521)
	at net.certiv.fluentmark.editor.FluentMkEditor.getPageModel(FluentMkEditor.java:504)
	at net.certiv.fluentmark.editor.FluentMkEditor.getPagePartAt(FluentMkEditor.java:816)
	at net.certiv.fluentmark.editor.FluentMkEditor.getMatchingPagePart(FluentMkEditor.java:800)
	at net.certiv.fluentmark.editor.FluentMkEditor.getShowInContext(FluentMkEditor.java:947)
	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.getContext(WorkbenchSourceProvider.java:410)
	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.updateActivePart(WorkbenchSourceProvider.java:476)
	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:294)
	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:289)
	at org.eclipse.ui.internal.services.WorkbenchSourceProvider$2.windowActivated(WorkbenchSourceProvider.java:248)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:1052)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench.fireWindowActivated(Workbench.java:1049)
	at org.eclipse.ui.internal.WorkbenchWindow$15.shellActivated(WorkbenchWindow.java:2314)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:89)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Decorations.WM_ACTIVATE(Decorations.java:1698)
	at org.eclipse.swt.widgets.Shell.WM_ACTIVATE(Shell.java:2277)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4840)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1657)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1114)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3492)
	at org.eclipse.ui.internal.quickaccess.SearchField.checkFocusLost(SearchField.java:534)
	at org.eclipse.ui.internal.quickaccess.SearchField$4.lambda$0(SearchField.java:247)
	at org.eclipse.ui.internal.quickaccess.SearchField$4$$Lambda$367/1369338774.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.ui.internal.Workbench$$Lambda$14/1772780918.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

![image](https://user-images.githubusercontent.com/1614482/32415701-a078d06a-c278-11e7-89d1-56323b1c54a4.png)

![image](https://user-images.githubusercontent.com/1614482/32415711-b85e60aa-c278-11e7-9a69-9740232eaabe.png)

**Comment by paulvi** [comment]
And the problem kept poping up.
It is not related to the first file opened. Possibly to layout of putting preview next to Editor.

**Comment by grosenberg** [comment]
Looks like Fluentmark is failing over an unexpected improper/invalid markdown source structure. Find which markdown file is causing this and attach.

**Comment by paulvi** [comment]
Not just one file, first  example is https://github.com/Nodeclipse/www.nodeclipse.org/blob/gh-pages/updates/java-start.md

Anyways, it should not be unsuppressible pop-up dialog, when just content is regarded wrong.

Just catch exceptions in write place.

**Comment by LeeWong** [comment]
Having the same issue.

**Comment by grosenberg** [comment]
Fixed.
