### ISSUE TITLE
FluentMark 1.0.0 renders Eclispe Photon unusable

### ISSUE THREAD

**Issue by ldesousa** [grosenberg/fluentmark#28]
I am unable to use to use Eclipse Photon, it is stuck in an exception loop that launches this dialogue:

![Loop exception](https://bugs.eclipse.org/bugs/attachment.cgi?id=274999)

This dialogue reappears immediately after being closed, making it impossible to use Eclipse. The exception reporter is presenting the following stack trace:

`Exception:java.lang.ClassCastException: net.certiv.fluentmark.model.PageRoot cannot be cast to net.certiv.fluentmark.model.PagePart
	 at net.certiv.fluentmark.model.PageRoot.addToParent(PageRoot.java:501)
	 at net.certiv.fluentmark.model.PageRoot.parse(PageRoot.java:410)
	 at net.certiv.fluentmark.model.PageRoot.updateModel(PageRoot.java:138)
	 at net.certiv.fluentmark.editor.FluentMkEditor.updatePageModel(FluentMkEditor.java:522)
	 at net.certiv.fluentmark.editor.FluentMkEditor.getPageModel(FluentMkEditor.java:505)
	 at net.certiv.fluentmark.editor.FluentMkEditor.getPagePartAt(FluentMkEditor.java:681)
	 at net.certiv.fluentmark.editor.FluentMkEditor.getMatchingPagePart(FluentMkEditor.java:665)
	 at net.certiv.fluentmark.editor.FluentMkEditor.getShowInContext(FluentMkEditor.java:822)
	 at org.eclipse.ui.internal.services.WorkbenchSourceProvider.getContext(WorkbenchSourceProvider.java:410)
	 at org.eclipse.ui.internal.services.WorkbenchSourceProvider.updateActivePart(WorkbenchSourceProvider.java:476)
	 at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:294)
	 at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:289)
	 at org.eclipse.ui.internal.services.WorkbenchSourceProvider$1.partOpened(WorkbenchSourceProvider.java:239)
	 at org.eclipse.ui.internal.PartService$5.run(PartService.java:131)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.PartService.partOpened(PartService.java:128)
	 at org.eclipse.ui.internal.WorkbenchPage$22.run(WorkbenchPage.java:5169)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.WorkbenchPage.firePartOpened(WorkbenchPage.java:5166)
	 at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$1(CompatibilityPart.java:121)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	 at org.eclipse.swt.widgets.Display.syncExec(Display.java:5831)
	 at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	 at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:196)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	 at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	 at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	 at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	 at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	 at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	 at org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl.setObject(PartImpl.java:435)
	 at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:130)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1012)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:557)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:541)
	 at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:70)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1012)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:778)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:749)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:743)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:727)
	 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:109)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	 at org.eclipse.swt.widgets.Display.syncExec(Display.java:5831)
	 at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	 at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:196)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	 at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	 at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	 at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	 at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	 at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	 at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:174)
	 at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.lambda$3(StackRenderer.java:1043)
	 at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1164)
	 at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3195)
	 at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1878)
	 at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:328)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	 at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	 at org.eclipse.equinox.launcher.Main.main(Main.java:1471)`

This issue was originally reported at [Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=537062), but folks there refused responsibility.

**Comment by grosenberg** [comment]
This is due to an old version being installed! Upgrade to ensure that the most recent version of Fluentmark (v1.1.1) is installed.

**Comment by ldesousa** [comment]
There is no FluentMark 1.1.1 at the Marketplace.
![fluentmark](https://user-images.githubusercontent.com/1137878/42989930-7ac6c612-8c01-11e8-949c-70729bbaeb3c.png)

**Comment by gdiamond** [comment]
It renders Version: Oxygen.3a Release (4.7.3a) unusable as well.

**Comment by grosenberg** [comment]
If the Marketplace is serving an old version, then go directly to the Certiv Tools update site at www.certiv.net/updates.
